version: "3.8"
services:
  url-scrape-resi:
    build:
      context: .
      dockerfile: Dockerfile
    image: url-scrape-resi:1.3.0
    container_name: url-scrape-resi
    restart: unless-stopped
    networks:
      - resi
    ports:
      - "3003:3003"
    shm_size: "512m"
    environment:
      - PORT=3003
      - PROXY_URL=${PROXY_URL:-}
      - BLOCK_MEDIA=True
      - TIMEOUT_MS=30000
      - WAIT_AFTER_LOAD=1500

networks:
  resi:
    driver: bridge
